name: push-latest

# trigger on master
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "!README.md"
      - "!CODE_OF_CONDUCT.md.md"

env:
  ORGANIZATION: "jenkins-x-images"
  IMAGE_NAME: "terraform-aws-cli"
  IMAGE_TAG: "latest"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build_push_latest:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker image build . --file Dockerfile --tag ghcr.io/$ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
        
      - name: Push image to registry
        run: docker push ghcr.io/$ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Save image
        run: docker image save -o $IMAGE_NAME-$IMAGE_TAG.tar ghcr.io/$ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar
